packages:
  - "."
  - "server"

allowBuilds:
  '@prisma/engines': false
  bcrypt: false
  esbuild: false
  prisma: false

onlyBuiltDependencies:
  - "@prisma/engines"
  - "bcrypt"
  - "esbuild"
  - "prisma"
